name: linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache: true

      - name: Download Dependencies and Run Vet
        run: |
          # Tải toàn bộ thư viện cần thiết về máy ảo
          go get -d ./...
          go mod tidy
          
          # Chạy kiểm tra lỗi bằng hàng chính chủ
          go vet ./...